# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: build
      - task: run

  build:
    env:
      CGO_ENABLED: 0
    cmds:
      - go build ./...

  run:
    cmds:
      - ./podgrab.exe
